# Matrices y Determinantes 

# Operaciones con Matrices
**Suma, Producto y Transposición**

Las operaciones fundamentales con matrices incluyen la suma, el producto y la transposición.

- **Suma de Matrices**: Dadas dos matrices $A$ y $B$ del mismo tamaño, la suma $A + B$ se obtiene sumando los elementos correspondientes de ambas matrices.

  $$
  (A + B)_{ij} = A_{ij} + B_{ij}
  $$

  La suma de matrices es conmutativa y asociativa. Es decir, para cualquier par de matrices $A$ y $B$ del mismo tamaño:
  $$
  A + B = B + A
  $$
  y para cualquier tres matrices $A$, $B$ y $C$ del mismo tamaño:
  $$
  (A + B) + C = A + (B + C)
  $$

- **Producto de Matrices**: Dadas dos matrices $A$ de tamaño $m \times n$ y $B$ de tamaño $n \times p$, el producto $AB$ es una matriz de tamaño $m \times p$ donde cada elemento se calcula como:

  $$
  (AB)_{ij} = \sum_{k=1}^n A_{ik} B_{kj}
  $$

  El producto de matrices no es conmutativo en general, es decir, para matrices $A$ y $B$, usualmente $AB \neq BA$. Sin embargo, el producto de matrices es asociativo y distributivo respecto a la suma:
  $$
  A(BC) = (AB)C
  $$
  y
  $$
  A(B + C) = AB + AC
  $$
  para matrices $A$, $B$ y $C$ de tamaños compatibles.

- **Transposición**: La transposición de una matriz $A$, denotada por $A^T$, es una nueva matriz donde las filas de $A$ se convierten en columnas y las columnas en filas.

  $$
  (A^T)_{ij} = A_{ji}
  $$

  La transposición tiene varias propiedades importantes:
  1. $(A^T)^T = A$
  2. $(A + B)^T = A^T + B^T$
  3. $(AB)^T = B^T A^T$

**Matrices Inversas**

Una matriz cuadrada $A$ de tamaño $n \times n$ tiene una inversa $A^{-1}$ si existe una matriz tal que:

$$
A A^{-1} = A^{-1} A = I_n
$$

donde $I_n$ es la matriz identidad de tamaño $n \times n$. La matriz identidad $I_n$ es una matriz diagonal con unos en la diagonal principal y ceros en todas las demás posiciones:
$$
I_n = \begin{pmatrix}
1 & 0 & \cdots & 0 \\
0 & 1 & \cdots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \cdots & 1
\end{pmatrix}
$$

Para que una matriz $A$ tenga una inversa, su determinante debe ser no cero ($\det(A) \neq 0$). La inversa de una matriz tiene las siguientes propiedades:
1. $(A^{-1})^{-1} = A$
2. $(AB)^{-1} = B^{-1} A^{-1}$
3. $(A^T)^{-1} = (A^{-1})^T$

Para encontrar la inversa de una matriz, se pueden usar varios métodos, como la eliminación de Gauss-Jordan o el método de cofactores.


# Determinantes
**Definición y Propiedades**

El determinante es una función que asigna un escalar a una matriz cuadrada. Para una matriz $A$ de tamaño $n \times n$, el determinante se denota por $\det(A)$ o $|A|$. El determinante se puede calcular mediante una variedad de métodos, incluyendo el desarrollo por cofactores.

- **Propiedades del Determinante**:
  1. $\det(A) = 0$ si y solo si $A$ es singular (no invertible).
  2. $\det(AB) = \det(A) \cdot \det(B)$ para cualquier par de matrices cuadradas $A$ y $B$ del mismo tamaño.
  3. $\det(A^T) = \det(A)$ para cualquier matriz cuadrada $A$.
  4. $\det(cA) = c^n \det(A)$ para cualquier matriz cuadrada $A$ de tamaño $n \times n$ y cualquier escalar $c$.

El determinante de una matriz $2 \times 2$ $A = \begin{pmatrix} a & b \\ c & d \end{pmatrix}$ se calcula como:
$$
\det(A) = ad - bc
$$

Para matrices de tamaño mayor, el determinante se puede calcular usando el desarrollo por cofactores. Para una matriz $3 \times 3$ $A = \begin{pmatrix} a & b & c \\ d & e & f \\ g & h & i \end{pmatrix}$, el determinante se calcula como:
$$
\det(A) = a(ei - fh) - b(di - fg) + c(dh - eg)
$$

**Teorema de Cramer**

El Teorema de Cramer proporciona una solución para sistemas de ecuaciones lineales utilizando determinantes. Para un sistema de ecuaciones lineales $AX = B$, donde $A$ es una matriz invertible de tamaño $n \times n$ y $X$ y $B$ son vectores columna, la solución viene dada por:

$$
X_i = \frac{\det(A_i)}{\det(A)} \quad \text{para} \quad i = 1, 2, \ldots, n
$$

donde $A_i$ es la matriz que se obtiene al reemplazar la columna $i$ de $A$ con el vector $B$.


# Ejemplos con Python

#### Ejemplo 1: Suma de Matrices


In [1]:
import numpy as np

# Definimos dos matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Calculamos la suma de las matrices
C = A + B
print("La suma de A y B es:")
print(C)


La suma de A y B es:
[[ 6  8]
 [10 12]]


#### Ejemplo 2: Producto de Matrices


In [2]:
import numpy as np

# Definimos dos matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Calculamos el producto de las matrices
C = np.dot(A, B)
print("El producto de A y B es:")
print(C)


El producto de A y B es:
[[19 22]
 [43 50]]


#### Ejemplo 3: Transposición de una Matriz


In [3]:
import numpy as np

# Definimos una matriz
A = np.array([[1, 2], [3, 4]])

# Calculamos la transposición de la matriz
A_T = np.transpose(A)
print("La transposición de A es:")
print(A_T)


La transposición de A es:
[[1 3]
 [2 4]]


#### Ejemplo 4: Inversa de una Matriz


In [4]:
import numpy as np

# Definimos una matriz
A = np.array([[1, 2], [3, 4]])

# Calculamos la inversa de la matriz
A_inv = np.linalg.inv(A)
print("La inversa de A es:")
print(A_inv)


La inversa de A es:
[[-2.   1. ]
 [ 1.5 -0.5]]


#### Ejemplo 5: Cálculo del Determinante


In [5]:
import numpy as np

# Definimos una matriz
A = np.array([[1, 2], [3, 4]])

# Calculamos el determinante de la matriz
det_A = np.linalg.det(A)
print("El determinante de A es:")
print(det_A)


El determinante de A es:
-2.0000000000000004


#### Ejemplo 6: Solución de un Sistema de Ecuaciones usando el Teorema de Cramer


In [6]:
import numpy as np

# Definimos la matriz de coeficientes y el vector de términos independientes
A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
B = np.array([5, 9, 7])

# Calculamos el determinante de A
det_A = np.linalg.det(A)

# Calculamos los determinantes de las matrices modificadas
A1 = A.copy()
A1[:, 0] = B
det_A1 = np.linalg.det(A1)

A2 = A.copy()
A2[:, 1] = B
det_A2 = np.linalg.det(A2)

A3 = A.copy()
A3[:, 2] = B
det_A3 = np.linalg.det(A3)

# Solucionamos el sistema usando el Teorema de Cramer
x1 = det_A1 / det_A
x2 = det_A2 / det_A
x3 = det_A3 / det_A

print("La solución del sistema es:")
print(f"x1 = {x1}, x2 = {x2}, x3 = {x3}")


La solución del sistema es:
x1 = 5.5813953488372166, x2 = -0.6976744186046513, x3 = -1.3720930232558137
