# Valores y Vectores Propios

**Valores Propios y Vectores Propios**

Dado un operador lineal $T: V \rightarrow V$ en un espacio vectorial $V$, un escalar $\lambda$ se denomina **valor propio** de $T$ si existe un vector no nulo $v \in V$ tal que:

$$
T(v) = \lambda v
$$

En este caso, $v$ se denomina **vector propio** asociado a $\lambda$. En términos matriciales, si $A$ es una matriz cuadrada de tamaño $n \times n$, $\lambda$ es un valor propio de $A$ si existe un vector no nulo $v$ tal que:

$$
Av = \lambda v
$$

Para encontrar los valores propios de una matriz $A$, resolvemos la ecuación característica:

$$
\det(A - \lambda I) = 0
$$

donde $I$ es la matriz identidad de tamaño $n \times n$ y $\lambda$ es un escalar. Los valores de $\lambda$ que satisfacen esta ecuación son los valores propios de $A$.

**Polinomio Característico**

El polinomio característico de una matriz $A$ de tamaño $n \times n$ es el polinomio definido por:

$$
p_A(\lambda) = \det(A - \lambda I)
$$

Este es un polinomio de grado $n$ cuyos coeficientes son funciones de los elementos de $A$. Las raíces del polinomio característico son los valores propios de $A$.

Propiedades importantes de los valores propios:
1. La suma de los valores propios de $A$ es igual a la traza de $A$ (la suma de los elementos en la diagonal principal de $A$).
2. El producto de los valores propios de $A$ es igual al determinante de $A$.

**Diagonalización**

Una matriz $A$ es **diagonalizable** si es similar a una matriz diagonal, es decir, si existe una matriz invertible $P$ tal que $P^{-1}AP$ es una matriz diagonal. En términos de operadores lineales, $T$ es diagonalizable si existe una base de $V$ compuesta por vectores propios de $T$.

Para que una matriz $A$ sea diagonalizable, es necesario y suficiente que $A$ tenga $n$ vectores propios linealmente independientes, donde $n$ es el tamaño de la matriz.

**Formas Canónicas**

Además de la diagonalización, existen otras formas canónicas de matrices que simplifican su estudio y aplicación:

- **Forma canónica de Jordan**: Una matriz cuadrada $A$ es similar a una matriz de Jordan, que es casi diagonal, con bloques de Jordan en la diagonal. Los bloques de Jordan corresponden a los valores propios y pueden tener unos en la subdiagonal inmediata.

- **Forma canónica racional**: Una matriz cuadrada $A$ puede transformarse en una forma canónica racional utilizando fracciones parciales. Esta forma es útil para la factorización y el análisis estructural de matrices.


**Criterios de Diagonalización**

Una matriz cuadrada $A$ es diagonalizable si cumple las siguientes condiciones:

1. El polinomio característico de $A$ tiene $n$ raíces (contando multiplicidades).
2. Para cada valor propio $\lambda$ de $A$, la dimensión del espacio propio correspondiente a $\lambda$ (es decir, el número de vectores propios linealmente independientes asociados a $\lambda$) es igual a la multiplicidad algebraica de $\lambda$ (es decir, el número de veces que $\lambda$ aparece como raíz del polinomio característico).

Formalmente, $A$ es diagonalizable si y solo si para cada valor propio $\lambda$, la multiplicidad geométrica (dimensión del espacio propio) de $\lambda$ es igual a su multiplicidad algebraica.

**Formas Canónicas**

- **Forma Canónica de Jordan**: La forma canónica de Jordan de una matriz $A$ es una matriz casi diagonal, con bloques de Jordan en la diagonal. Cada bloque de Jordan está asociado a un valor propio $\lambda$ y tiene la forma:

  $$
  J_k(\lambda) = \begin{pmatrix}
  \lambda & 1 & 0 & \cdots & 0 \\
  0 & \lambda & 1 & \cdots & 0 \\
  0 & 0 & \lambda & \cdots & 0 \\
  \vdots & \vdots & \vdots & \ddots & 1 \\
  0 & 0 & 0 & \cdots & \lambda
  \end{pmatrix}
  $$

  La matriz $A$ es similar a una matriz de Jordan, lo que significa que existe una matriz invertible $P$ tal que $P^{-1}AP$ es una matriz de Jordan.

- **Forma Canónica Racional**: La forma canónica racional de una matriz $A$ se obtiene mediante descomposición en fracciones parciales. Esta forma es útil para estudiar la estructura de $A$ y para aplicaciones en teoría de control y otros campos.

Para transformar una matriz en su forma canónica de Jordan o en su forma canónica racional, se utilizan técnicas avanzadas de álgebra lineal, incluyendo la descomposición en espacios propios generalizados y el uso de polinomios mínimos.


# Ejemplos con Python

#### Ejemplo 1: Cálculo de Valores Propios y Vectores Propios

In [1]:
import numpy as np

# Definimos una matriz
A = np.array([[4, -2], [1, 1]])

# Calculamos los valores propios y los vectores propios
valores_propios, vectores_propios = np.linalg.eig(A)

print("Valores propios:")
print(valores_propios)
print("Vectores propios:")
print(vectores_propios)

Valores propios:
[3. 2.]
Vectores propios:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


#### Ejemplo 2: Diagonalización de una Matriz

In [3]:
import numpy as np

# Definimos una matriz
A = np.array([[4, -2], [1, 1]])

# Calculamos los valores propios y los vectores propios
valores_propios, vectores_propios = np.linalg.eig(A)

# Verificamos si la matriz es diagonalizable
if np.linalg.matrix_rank(vectores_propios) == A.shape[0]:
    P = vectores_propios
    D = np.diag(valores_propios)
    P_inv = np.linalg.inv(P)
    A_diagonal = P @ D @ P_inv
    print("La matriz es diagonalizable.")
    print("Matriz diagonal:")
    print(D)
    print("Matriz de cambio de base:")
    print(P)
else:
    print("La matriz no es diagonalizable.")

La matriz es diagonalizable.
Matriz diagonal:
[[3. 0.]
 [0. 2.]]
Matriz de cambio de base:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


#### Ejemplo 3: Forma Canónica de Jordan

In [5]:
import numpy as np
from sympy import Matrix

# Definimos una matriz
A = Matrix([[5, 4, 2], [0, 1, -1], [0, 2, 3]])

# Calculamos la forma canónica de Jordan
J, P = A.jordan_form()

print("Forma canónica de Jordan:")
print(J)
print("Matriz de cambio de base:")
print(P)

Forma canónica de Jordan:
Matrix([[1, 1/5 + 3*I/5, 1/5 - 3*I/5], [0, -1/2 - I/2, -1/2 + I/2], [0, 1, 1]])
Matriz de cambio de base:
Matrix([[5, 0, 0], [0, 2 - I, 0], [0, 0, 2 + I]])
